xgboost:
  hyperparams:
    objective: binary:logistic
    random_state: 42
    eval_metric: auc
    enable_categorical: true
    n_jobs: -1
    grow_policy: lossguide
    learning_rate: 0.01184506423565172
    subsample: 0.9843350621400545
    colsample_bytree: 0.23379345015134234
    colsample_bynode: 0.9101617347853203
    min_child_weight: 66.21019772018973
    reg_lambda: 0.02222906905676631
    gamma: 0.7622597484090166
    max_leaves: 48
    n_estimators: 3063
  target_encoding_smoothing: 50
  features:
    - avg_annuity_vs_actual_annuity
    - bureau_balance_is_delincuency_sum_loan_1
    - closed_days_credit_update_closed_max
    - instalments_completion_ratio_mean
    - last_365_instalments_days_of_delinquency_mean
    - implied_interest_rate_mean
    - last_365_instalments_is_delinquency_mean
    - active_amt_credit_sum_active_max
    - ratio_credit_to_goods_max
    - ext_source_2
    - active_completetitud_ratio_active_min
    - closed_amt_credit_sum_debt_closed_mean
    - payment_trend
    - active_id_curr_active_count
    - wallsmaterial_mode
    - flag_document_3
    - code_reject_reason_prev_1
    - ext_2_x_3
    - bureau_balance_status_score_mean_loan_1
    - active_amt_annuity_active_std
    - ext_source_3
    - region_raiting_client_city
    - amt_goods_price_max
    - amt_down_payment_sum
    - days_and_insurance_information_are_missing_mean
    - education_type_Secondary / secondary special
    - amt_credit
    - closed_days_credit_update_closed_min
    - name_income_type
    - days_termination_prev_1
    - building_score_mean
    - closed_ratio_credit_annuity_closed_max
    - code_gender
    - bureau_days_enddate_fact_loan_1
    - bureau_credit_type_loan_1
    - credit_duration
    - implied_interest_rate_max
    - last_6_cash_balance_count_instalment_future_min
    - occupation_type
    - last_6_credit_card_balance_limit_ratio_mean
    - bureau_balance_is_delincuency_mean_loan_1
    - bureau_amt_credit_max_overdue_loan_1
    - amt_annuity
    - implied_interest_rate_std
    - closed_amt_credit_sum_debt_closed_std
    - ext_source_1
    - ratio_credit_to_goods_mean
    - organization_type
    - last_6_credit_card_balance_limit_ratio_max
    - ratio_days_employed_days_lived
    - last_6_cash_balance_sk_dpd_def_sum
    - amt_req_credit_breau_day
    - active_amt_credit_max_overdue_active_max
    - instalments_days_of_delinquency_max_max
    - active_have_amt_credit_sum_overdue_active_sum
    - bureau_amt_credit_sum_debt_is_missing_loan_1
    - days_birth
    - days_decision_mean
    - days_decision_min
    - closed_amt_credit_sum_closed_sum
    - last_6_cash_balance_sk_dpd_mean
    - def_60_cnt_social_circle
    - last_365_instalments_amt_payment_min
    - instalments_amt_instalment_sum_sum
    - active_completetitud_ratio_active_mean
    - own_car_age
    - last_6_cash_balance_amount_advanced_payment_max
    - def_30_cnt_social_circle
    - flag_own_realty
    - education_type_Higher_education
    - ratio_debt_age
    - documents_count
    - family_status
    - applications_count
    - building_score_sum
    - active_amt_annuity_is_missing_active_sum
    - region_raiting_client
    - amt_req_credit_breau_qrt
    - ext_1_x_3
    - diff_application_credit_max
    - active_days_credit_enddate_active_mean
    - instalments_is_delinquency_mean_mean
    - instalments_extra_instalament_mean_mean
    - ext_1_x_2
    - active_amt_credit_max_overdue_active_sum
    - last_6_credit_card_completion_ratio
    - name_contract_type
    - last_365_instalments_extra_instalament_mean
    - credit_card_is_over_the_limit_mean_mean
    - ext_source_1_is_missing
    - last_6_cash_balance_count_instalment_future_max
    - ratio_good_credit
    - closed_amt_credit_sum_closed_max
    - last_365_instalments_completion_ratio
    - instalments_amt_payment_sum_sum
    - days_id_publish
    - credit_card_cnt_drawings_atm_current_mean_mean
    - instalments_days_of_delinquency_mean_prev_1
    - name_seller_industry_prev_1
    - last_90_instalments_completion_ratio
    - ext_source_mean
    - bureau_days_credit_enddate_loan_1
    - flag_not_live_city
    - instalments_days_of_underpayment_max_max
    - kui_ratio
    - closed_amt_credit_max_overdue_closed_mean
    - days_employed
    - instalments_amount_of_versions_in_sequence_prev_1
    - days_last_due_1st_version_prev_1
    - bureau_completetitud_ratio_loan_1
    - amt_goods_price
    - instalments_days_of_delinquency_mean_mean
    - antique_annuity_vs_actual_annuity
    - instalment_income_ratio
  categorical_features:
    -organization_type
    -occupation_type
 
lgbm:
  hyperparams:
    n_estimators: 4693
    learning_rate: 0.007553343326775532
    num_leaves: 37
    min_child_samples: 220
    min_child_weight: 0.0028908609938903796
    max_depth: -1
    subsample: 0.8389118020044092
    subsample_freq: 3
    colsample_bytree: 0.5616610992553818
    reg_alpha: 2.24385145804699e-07
    reg_lambda: 7.747405452353306
    min_split_gain: 0.786374413940256
    random_state: 42
    cat_smooth: 7.237675739015409
    cat_l2: 75.34738775153713
    n_jobs: -1
    objective: 'binary'
    force_col_wise: true
    importance_type: 'gain'
  target_encoding_smoothing: 2.5821099004254604
  features:    
  - avg_annuity_vs_actual_annuity
  - credit_card_cnt_drawings_current_max_prev_1
  - active_credit_type_mortgage_active_mean
  - ext_source_1
  - instalments_amount_of_versions_in_sequence_max
  - active_credit_type_microloan_active_mean
  - name_contract_status_canceled_mean
  - def_30_cnt_social_circle
  - last_6_cash_balance_amount_advanced_payment_sum
  - documents_count
  - instalments_is_delinquency_sum_sum
  - closed_id_curr_closed_count
  - education_type_Secondary / secondary special
  - last_6_credit_card_desesperation_ratio_mean
  - active_amt_credit_max_overdue_active_sum
  - amt_req_credit_breau_qrt
  - amt_goods_price
  - days_employed
  - active_credit_type_consumer_credit_active_sum
  - closed_balance_is_delincuency_mean_closed_mean
  - instalments_extra_instalament_mean_mean
  - days_last_phone_change
  - active_id_curr_active_count
  - amt_annuity
  - bureau_amt_credit_sum_loan_1
  - active_amt_credit_max_overdue_active_max
  - credit_card_amt_balance_max_max
  - last_90_instalments_completion_ratio
  - credit_card_is_over_the_limit_mean_mean
  - organization_type
  - last_365_instalments_completion_ratio
  - instalments_log_amt_instalment_std_prev_1
  - active_amt_credit_sum_debt_active_sum
  - cash_balance_sk_dpd_def_mean_mean
  - active_log_amt_credit_sum_active_mean
  - closed_amt_credit_max_overdue_closed_mean
  - active_log_amt_credit_sum_active_std
  - days_decision_spread
  - instalments_log_amt_payment_std_prev_1
  - total_interest_charged_max
  - instalments_days_of_delinquency_mean_prev_1
  - last_365_instalments_is_delinquency_mean
  - ratio_debt_age
  - active_amt_credit_sum_active_max
  - closed_days_enddate_fact_closed_max
  - education_type_Higher_education
  - last_6_credit_card_completion_ratio
  - bureau_amt_credit_max_overdue_loan_1
  - instalments_completion_ratio_mean
  - active_amt_credit_sum_active_sum
  - active_days_credit_enddate_active_max
  - family_status
  - instalments_amt_instalment_sum_sum
  - bureau_amt_credit_sum_debt_loan_1
  - closed_days_credit_update_closed_max
  - instalments_days_in_advance_max_max
  - bureau_credit_type_loan_1
  - active_days_credit_active_max
  - flag_document_3
  - amt_annuity_median
  - credit_card_cnt_drawings_atm_current_mean_mean
  - closed_amt_credit_sum_closed_std
  - log_amt_annuity_mean
  - ratio_credit_to_goods_min
  - active_days_credit_active_mean
  - days_registration
  - last_6_cash_balance_count_instalment_future_min
  - bureau_days_credit_enddate_loan_1
  - closed_days_credit_closed_max
  - closed_amt_credit_sum_closed_mean
  - days_decision_prev_1
  - bureau_days_credit_enddate_first_cluster_values_loan_1
  - active_days_credit_enddate_active_mean
  - occupation_type
  - product_combination_prev_1
  - log_amt_annuity_std
  - bureau_completetitud_ratio_loan_1
  - instalments_days_of_delinquency_mean_mean
  - days_birth
  - days_decision_min
  - instalments_amt_payment_sum_max
  - days_decision_mean
  - ratio_days_employed_days_lived
  - name_income_type
  - amt_down_payment_sum
  - instalments_days_of_underpayment_max_max
  - credit_duration
  - kui_ratio
  - last_90_instalments_amt_instalment_min
  - closed_amt_credit_sum_closed_sum
  - flag_not_live_city
  - region_raiting_client_city
  - implied_interest_rate_std
  - implied_interest_rate_mean
  - ext_source_mean
  - instalment_income_ratio
  - name_contract_status_refused_mean
  - instalments_is_delinquency_mean_mean
  - ext_2_x_3
  - ratio_credit_to_goods_mean
  - instalments_amt_payment_sum_sum
  - amt_credit
  - code_gender
  - last_365_instalments_days_of_delinquency_mean
  - ext_source_2
  - region_population
  - last_6_cash_balance_count_instalment_future_max
  - own_car_age
  - active_completetitud_ratio_active_mean
  - last_6_credit_card_balance_limit_ratio_max
  - ratio_good_credit
  - days_id_publish
  - ratio_annuity_income
  - implied_interest_rate_max
  - active_completetitud_ratio_active_min
  - wallsmaterial_mode
  - ext_source_3
  - ext_1_x_2
  - ext_1_x_3
  - bureau_days_credit_loan_1
  - antique_annuity_vs_actual_annuity
  
  categorical_features: 
    -organization_type
    -occupation_type
    -bureau_credit_type_loan_1
    -wallsmaterial_mode




